export const LOADING = 'LOADING';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const LOGIN_ERROR = 'SIGNIN_ERROR';
export const LOGIN_SUCCESS = 'SIGNIN_SUCCESS';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const BUCKETLISTS_SUCCESS = 'BUCKETLISTS_SUCCESS';
export const BUCKETLISTS_ERROR = 'BUCKETLISTS_ERROR';
export const SINGLEBUCKET_SUCCEESS = 'SINGLEBUCKET_SUCCEESS';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const SINGLELIST_SUCCESS = 'SINGLELIST_SUCCESS';


